name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09a6c30f0e0e843c58f455b3878aa4d17d983bfbaa3fca7e2a9e7504d7f9ecad"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
