name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e27ad1e7a29b8b1f39bd1d1adc686136493ea269f29dbb65aa7015cc0a946bf"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
