name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d1143b577fcdb56be0758b986b9192f23e679ea720f98fcc12541885e25bf07"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
