name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eba11bdfab6d1e0935166e4052d88d1445b1662c85bbacb317fadcf3cba65dc5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
